import re, os, sys, hashlib, urllib.request

UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36'
OUT = 'assets/fonts'
os.makedirs(OUT, exist_ok=True)

FAMILIES = {
  'Archivo': 'https://fonts.googleapis.com/css2?family=Archivo:wght@500;600;700;800&display=swap',
  'Archivo:wdth,wght@125,700': 'https://fonts.googleapis.com/css2?family=Archivo:wght@700;800&display=swap',  # placeholder
  'IBM Plex Mono': 'https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&display=swap',
  'Inter Tight': 'https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;500;600&display=swap',
}
# keep it simple: 3 families
FAMILIES = {
  'Archivo': 'https://fonts.googleapis.com/css2?family=Archivo:wght@500;600;700;800&display=swap',
  'IBM Plex Mono': 'https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&display=swap',
  'Inter Tight': 'https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;500;600&display=swap',
}

def get(url):
    req = urllib.request.Request(url, headers={'User-Agent': UA})
    return urllib.request.urlopen(req).read()

out_css = ["/* Kniff — self-hosted fonts (OFL). Generated by scripts/fetch-fonts.py */\n"]
kept = 0
for fam, url in FAMILIES.items():
    css = get(url).decode('utf-8')
    # split into @font-face blocks, each preceded by a /* subset */ comment
    blocks = re.split(r'(?=/\*\s*[a-z0-9-]+\s*\*/)', css)
    for b in blocks:
        m = re.match(r'/\*\s*([a-z0-9-]+)\s*\*/', b.strip())
        if not m: continue
        subset = m.group(1)
        if subset not in ('latin', 'latin-ext'):
            continue
        ff = re.search(r'@font-face\s*\{[^}]*\}', b, re.S)
        if not ff: continue
        rule = ff.group(0)
        wght = re.search(r'font-weight:\s*(\d+)', rule)
        style = re.search(r'font-style:\s*(\w+)', rule)
        u = re.search(r'url\((https://fonts\.gstatic\.com/[^)]+\.woff2)\)', rule)
        if not u: continue
        w = wght.group(1) if wght else '400'
        st = style.group(1) if style else 'normal'
        slug = re.sub(r'[^a-z0-9]+', '-', fam.lower()).strip('-')
        fname = f'{slug}-{w}-{st}-{subset}.woff2'
        data = get(u.group(1))
        with open(os.path.join(OUT, fname), 'wb') as fh:
            fh.write(data)
        rule2 = rule.replace(u.group(1), fname)
        out_css.append(rule2 + '\n')
        kept += 1
        print(f'  {fam:16} {w:4} {st:7} {subset:9} -> {fname} ({len(data)} B)')

with open(os.path.join(OUT, 'kniff-fonts.css'), 'w') as fh:
    fh.write('\n'.join(out_css))
print(f'\n{kept} faces, css -> {OUT}/kniff-fonts.css')
